export const UNIT_TYPES = [
  "BAGS",
  "BALE",
  "BUNDLES",
  "BUCKLES",
  "BILLION OF UNITS",
  "BOX",
  "BOTTLES",
  "BUNCHES",
  "CANS",
  "CUBIC METERS",
  "CUBIC CENTIMETERS",
  "CENTI METERS",
  "CARTONS",
  "DOZENS",
  "DRUMS",
  "GREAT GROSS",
  "GRAMMES",
  "GROSS",
  "GROSS YARDS",
  "KILOGRAMS",
  "KILOLITRE",
  "KILOMETRE",
  "LITRES",
  "MILILITRE",
  "METERS",
  "METRIC TON",
  "NUMBERS",
  "OTHERS",
  "PACKS",
  "PIECES",
  "PAIRS",
  "QUINTAL",
  "ROLLS",
  "SETS",
  "SQUARE FEET",
  "SQUARE METERS",
  "SQUARE YARDS",
  "TABLETS",
  "TEN GROSS",
  "THOUSANDS",
  "TONNES",
  "TUBES",
  "US GALLONS",
  "UNITS",
  "YARDS"
];

export const getUqcCode = (unitType: string): string => {
  const mapping: Record<string, string> = {
    "BAGS": "BGS",
    "BALE": "BAL",
    "BUNDLES": "BDL",
    "BUCKLES": "BKL",
    "BILLION OF UNITS": "BOU",
    "BOX": "BOX",
    "BOTTLES": "BTL",
    "BUNCHES": "BUN",
    "CANS": "CAN",
    "CUBIC METERS": "CBM",
    "CUBIC CENTIMETERS": "CCM",
    "CENTI METERS": "CMS",
    "CARTONS": "CTN",
    "DOZENS": "DOZ",
    "DRUMS": "DRM",
    "GREAT GROSS": "GGK",
    "GRAMMES": "GMS",
    "GROSS": "GRS",
    "GROSS YARDS": "GYD",
    "KILOGRAMS": "KGS",
    "KILOLITRE": "KLR",
    "KILOMETRE": "KME",
    "LITRES": "LTR",
    "MILILITRE": "MLT",
    "METERS": "MTR",
    "METRIC TON": "MTS",
    "NUMBERS": "NOS",
    "OTHERS": "OTH",
    "PACKS": "PAC",
    "PIECES": "PCS",
    "PAIRS": "PRS",
    "QUINTAL": "QTL",
    "ROLLS": "ROL",
    "SETS": "SET",
    "SQUARE FEET": "SQF",
    "SQUARE METERS": "SQM",
    "SQUARE YARDS": "SQY",
    "TABLETS": "TBS",
    "TEN GROSS": "TGM",
    "THOUSANDS": "THD",
    "TONNES": "TON",
    "TUBES": "TUB",
    "US GALLONS": "UGS",
    "UNITS": "UNT",
    "YARDS": "YDS"
  };
  return mapping[unitType] || "OTH";
};
